# Autogenerated wrapper script for GAP_lib_jll for any
JLLWrappers.@generate_wrapper_header("GAP_lib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
